// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZJdgYHDWzXZVav8b3rtKaJhqiOroPYw',
    appId: '1:133943267284:web:dcf940a5ffbc2479f45041',
    messagingSenderId: '133943267284',
    projectId: 'mm45m-f8e08',
    authDomain: 'mm45m-f8e08.firebaseapp.com',
    storageBucket: 'mm45m-f8e08.appspot.com',
    measurementId: 'G-805JW3360R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0k854x_LTIvYHhCP27BPqe0Ltzzwut-8',
    appId: '1:133943267284:android:a093349d10e10fb4f45041',
    messagingSenderId: '133943267284',
    projectId: 'mm45m-f8e08',
    storageBucket: 'mm45m-f8e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UEIPIQei8FBWD9RNW02cNcz_N-5-n5w',
    appId: '1:133943267284:ios:fd31dd0b214c330bf45041',
    messagingSenderId: '133943267284',
    projectId: 'mm45m-f8e08',
    storageBucket: 'mm45m-f8e08.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0UEIPIQei8FBWD9RNW02cNcz_N-5-n5w',
    appId: '1:133943267284:ios:fd31dd0b214c330bf45041',
    messagingSenderId: '133943267284',
    projectId: 'mm45m-f8e08',
    storageBucket: 'mm45m-f8e08.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
